#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
/usr/libexec/kf5/polkit-kde-authentication-agent-1 &
.$HOME/.config/polybar/launch.sh &

#__autostart programs
pgrep -x picom  > /dev/null || picom &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x dunst > /dev/null || dunst &
pgrep -x variety > /dev/null || variety &
#pgrep -x blueman > /dev/null || blueman &
#pgrep -x volumeicon > /dev/null || volumeicon &

bspc monitor -d  1 2 3 4 5 6 7 8 9

bspc config border_width         3
bspc config window_gap          0 #12

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config honor_size_hints     false
#bspc config initial_polarity     second_child 
#bspc config node_focus			 above
#bspc config automatic_scheme     alternate
#bspc config focused -l above     true

bspc config normal_border_color		      "#333333"
bspc config focused_border_color	      "#285577"
#bspc config active_border_color	          "#1e1e1e"
#bspc config presel_feedback_color	      "#a52a2a"
#bspc config urgent_border_color 	      "#ee82ee"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Variety state=floating follow=on
#bspc rule -a Chromium desktop='^2'
