#!/usr/bin/env bash

#__basic setup
#$HOME/.config/polybar/launch.sh &
/usr/libexec/kf5/polkit-kde-authentication-agent-1 &

picom -f ;
nm-applet ;
dunst ;
variety ;
kitty ;

bspc monitor -d  1 2 3 4 5 6 7 8 9

#bspc config border_width         2
#bspc config window_gap          0 #12

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config honor_size_hints     false
#bspc config initial_polarity     second_child 
#bspc config node_focus			 above
#bspc config automatic_scheme     alternate
#bspc config focused -l above     true

#bspc config normal_border_color		      "#ffffff3a"
#bspc config active_border_color	          "#1e1e1e"
#bspc config focused_border_color	      "#64A4E2"
#bspc config presel_feedback_color	      "#a52a2a"
#bspc config urgent_border_color 	      "#ee82ee"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Variety state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Polybar state=floating
#bspc rule focus=on layer=above
